spring:
  application:
    name: Config-Dev
  port: 8085
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    rigister-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

