meter:
  allowedCounterList:
    - "ChargeVolume-GoPayment_AWS_"
    - "ChargeVolume-MerchantServiceCenter"
    - "ChargeVolume-PaymentsWorkflow"
    - "ChargeVolume-GoPayment_v3_"
    - "ChargeVolume-QBDT__MerchantAccount_"
    - "ChargeVolume-CounterPart_Portal"
    - "ChargeVolume-SCS"
    - "ChargeVolume-QBDT_Card"
    - "ChargeVolume-BigCommerce"
    - "ChargeVolume-QB-POS"
    - "ChargeVolume-QBO"
    - "ChargeVolume-Revel"
    - "ChargeVolume-Shopify"
    - "ChargeVolume-ThirdPartyApp"
    - "ECheckVolume-GoPayment_AWS_"
    - "ECheckVolume-MerchantServiceCenter"
    - "ECheckVolume-PaymentsWorkflow"
    - "ECheckVolume-GoPayment_v3_"
    - "ECheckVolume-QBDT__MerchantAccount_"
    - "ECheckVolume-CounterPart_Portal"
    - "ECheckVolume-QBDT_Card"
    - "ECheckVolume-BigCommerce"
    - "ECheckVolume-QB-POS"
    - "ECheckVolume-QBO"
    - "ECheckVolume-Revel"
    - "ECheckVolume-Shopify"
    - "ECheckVolume-ThirdPartyApp"
    - "TxnCount-Auth"
    - "TxnCount-BigCommerce"
    - "TxnCount-EMV_Sale"
    - "TxnCount-Capture"
    - "TxnCount-QBDT_Card"
    - "TxnCount-QBO"
    - "TxnCount-QB-POS"
    - "TxnCount-MerchantServiceCenter"
    - "TxnCount-QBDT__MerchantAccount_"
    - "TxnCount-PaymentsWorkflow"
    - "TxnCount-GoPayment_AWS_"
    - "TxnCount-GoPayment_v3_"
    - "TxnCount-CounterPart_Portal"
    - "TxnCount-SCS"
    - "TxnCount-Sale"
    - "TxnCount-Refund"
    - "TxnCount-Revel"
    - "TxnCount-Shopify"
    - "TxnCount-Sale"
    - "TxnCount-Void"
    - "TxnCount-ThirdPartyApp"
    - "Overall"
    - "Auth"
    - "Capture"
    - "Refund"
    - "Auth"
    - "Void"
    - "Visa"
    - "MasterCard"
    - "American_Express"
    - "Diners_Club"
    - "Discover"
    - "RecurringPayments"
    - "Risk"
    - "PayPal"
    - "Sale"
  kpiCounterBlockedList:
    - "ECheckVolume-"
    - "TxnCount-"
    - "ChargeVolume-"
    - "-ApprovalCount"
    - "-DeclineCount"
    - "-ChargeVolume"