spring:
  datasource:
    url: jdbc:h2:mem:IMSOWN;INIT=CREATE SCHEMA IF NOT EXISTS IMSOWN;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    #schema: classpath:/data/h2db/schema-h2.sql
    #data: classpath:/data/h2db/data-h2.sql
    continue-on-error: true
    platform: h2
    ucm:
      default-auto-commit: true

  cloud:
    compatibility-verifier:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
gateway:
  hostResponseCodeMapping:
    522:
      declined: false
      resultCode: 5006
      invalidRequest: true
      invalidRequestCode: "PMT_4000"
      invalidRequestMessage: "ExpirationMonth/ExpirationYear. is invalid."
      invalidRequestDetail: "ExpirationMonth/ExpirationYear."
    530:
      declined: true
      resultCode: 5008
      invalidRequest: false
